version: "3.7"
services:
  backend:
    build:
      args:
        user: josembarboteo
        uid: 1000
      context: ./
      dockerfile: Docker/Dockerfile
    image: airzone/backend:latest
    container_name: AirzoneBackend
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - AirzoneDev
  db:
    image: mysql:8.0
    container_name: AirzoneDatabase
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./Docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - AirzoneDev
  nginx:
    image: nginx:alpine
    container_name: AirzoneReverseProxy
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./Docker/nginx:/etc/nginx/conf.d/
    networks:
      - AirzoneDev
networks:
  AirzoneDev:
    driver: bridge